all: source operator sink

source:
	cd /Users/julien/dev/demonstrations/20220425-zf-gamepad-controller/source-gamepad && cargo clean

operator:
	cd /Users/julien/dev/demonstrations/20220425-zf-gamepad-controller/operator-twist && cargo clean

sink:
	cd /Users/julien/dev/demonstrations/20220425-zf-gamepad-controller/sink-serialize && cargo clean
